services:  
 mysql:
  image: mysql:8.0
  volumes:
  - calculator-mysql-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: secret
   MYSQL_DATABASE: Calculator
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:3306"]
   interval: 10s
   timeout: 5s
   retries: 3

 sqaure:
  image: vikrantsingh99/square:2.9
  ports:
   - 9090:9090
  working_dir: /usr/src/app
  depends_on:
      mysql:
       condition: service_healthy
  

 cube:
  image: vikrantsingh99/cube:1.4
  ports:
   - 5050:5050
  working_dir: /usr/src/app
  depends_on:
      mysql:
       condition: service_healthy

 fibonacci:
  image: vikrantsingh99/fibonacci:1.3
  ports:
   - 4040:4040
  working_dir: /usr/src/app
  depends_on:
      mysql:
       condition: service_healthy

 metrices:
  image: vikrantsingh99/metrices:1.2
  ports:
   - 2020:2020
  working_dir: /usr/src/app
  depends_on:
      mysql:
       condition: service_healthy

 calculator-app:
  image: vikrantsingh99/calculator-app:1.4
  ports:
   - 3000:3000
  working_dir: /app
  depends_on:
      mysql:
       condition: service_healthy

volumes:
 calculator-mysql-data: